baseurl: https://example.com
languageCode: en-us
theme: 
  - stack
  - gallery
  - hugo-notice
paginate: 5
title: Malinkang's Blog
copyright: malinkang

# Change it to your Disqus shortname before using
disqusShortname: hugo-theme-stack

# GA Tracking ID
googleAnalytics: G-G84J9N38RL

# Theme i18n support
# Available values: ar, bn, ca, de, el, en, es, fr, hu, id, it, ja, ko, nl, pt-br, th, uk, zh-cn, zh-hk, zh-tw
DefaultContentLanguage: en

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage: false

permalinks:
    post: /p/:slug/
    page: /:slug/

params:
  mainSections:
    - posts
  featuredImageField: image
  rssFullContent: true
  favicon:  # e.g.: favicon placed in `static/favicon.ico` of your site folder, then set this field to `/favicon.ico` (`/` is necessary)
  footer:
    since: 2013
    customText:
  dateFormat:
      published: Jan 02, 2006
      lastUpdated: Jan 02, 2006 15:04 MST
  sidebar:
      emoji: 🍥
      subtitle: 采菊东篱下，悠然见南山。
      avatar:
        enabled: true
        local: true
        src: images/avatar.jpeg

  article:
    math: false
    toc: true
    readingTime: true
    license:
        enabled: true
        default: Licensed under CC BY-NC-SA 4.0
  comments:
    enabled: true
    provider: giscus
    disqusjs:
      shortname:
      apiUrl:
      apiKey:
      admin:
      adminLabel:
    utterances:
      repo:
      issueTerm: pathname
      label:
    remark42:
      host:
      site:
      locale:
    vssue:
      platform:
      owner:
      repo:
      clientId:
      clientSecret:
      autoCreateIssue: false
    # Waline client configuration see: https://waline.js.org/en/reference/component.html
    waline:
      serverURL:
      lang:
      pageview:
      emoji:
          - https://unpkg.com/@waline/emojis@1.0.1/weibo
      requiredMeta:
          - name
          - email
          - url
      locale:
          admin: Admin
          placeholder:
    twikoo:
      envId:
      region:
      path:
      lang:
    # See https://cactus.chat/docs/reference/web-client/#configuration for description of the various options
    cactus:
        defaultHomeserverUrl: "https://matrix.cactus.chat:8448"
        serverName: "cactus.chat"
        siteName: "" # You must insert a unique identifier here matching the one you registered (See https://cactus.chat/docs/getting-started/quick-start/#register-your-site)
    giscus:
      repo: malinkang/malinkang
      repoID: MDEwOlJlcG9zaXRvcnkzMTUwNzEyODU=
      category: General
      categoryID: DIC_kwDOEsebNc4CbSPg
      mapping: pathname
      lightTheme: light
      darkTheme: dark
      reactionsEnabled: 1
      emitMetadata: 0

    gitalk:
      owner:
      admin:
      repo:
      clientID:
      clientSecret:

    cusdis:
      host:
      id:
  widgets:
      homepage:
          - type: search
          - type: archives
            params:
                limit: 5
          - type: categories
            params:
                limit: 10
          - type: tag-cloud
            params:
                limit: 10
      page:
          - type: toc
  opengraph:
      twitter:
          # Your Twitter username
          site:
          # Available values: summary, summary_large_image
          card: summary_large_image

  defaultImage:
      opengraph:
          enabled: false
          local: false
          src:

  colorScheme:
      # Display toggle
      toggle: true
      # Available values: auto, light, dark
      default: auto
  imageProcessing:
      cover:
          enabled: true
      content:
          enabled: true

### Custom menu
### See https://docs.stack.jimmycai.com/configuration/custom-menu.html
### To remove about, archive and search page menu item, remove `menu` field from their FrontMatter
#https://tabler.io/icons
defaultContentLanguage: zh-cn
menu:
    main: 
      - identifier: home
        name: 首页
        url: /
        weight: -100
        params:
          icon: home
          newTab: false
      - identifier: book
        name: 阅读
        url: https://malinkang.notion.site/book
        weight: 100
        params:
          icon: book
          newTab: true
      - identifier: workout
        name: 运动
        url: https://malinkang.notion.site/workouts
        weight: 101
        params:
          icon: run
          newTab: true
      - identifier: movie
        name: 观影
        url: https://malinkang.notion.site/workouts
        weight: 102
        params:
          icon: movie
          newTab: true
      - identifier: podcast
        name: 播客
        url: https://malinkang.notion.site/workouts
        weight: 103
        params:
          icon: broadcast
          newTab: true
    social:
      - identifier: github
        name: GitHub
        url: https://github.com/malinkang
        weight: 1
        params:
            icon: brand-github
      - identifier: x
        name: X
        url: https://x.com/malinkang
        weight: 2
        params:
            icon: brand-x
      - identifier: weibo
        name: 微博
        url: https://www.weibo.com/malinkang
        weight: 4
        params:
            icon: brand-weibo
      - identifier: douban
        name: 豆瓣
        url: https://www.douban.com/people/malinkang/
        weight: 8
        params:
            icon: brand-douban
      - identifier: bilibili
        name: Bilibili
        url: https://space.bilibili.com/27440979
        weight: 7
        params:
            icon: brand-bilibili      
      - identifier: telegram
        name: Telegram
        weight: 3
        url: https://t.me/malinkang
        params:
            icon: brand-telegram
      - identifier: instagram
        name: Instagram
        url: https://www.instagram.com/malinkang
        weight: 5
        params:
            icon: brand-instagram      
      - identifier: mastodon
        name: Mastodon
        url: https://mastodon.social/@malinkang
        weight: 6
        params:
            icon: brand-mastodon   
      - identifier: strava
        name: Strava
        url: https://www.strava.com/athletes/20840511
        weight: 10
        params:
            icon: brand-strava
      - identifier: zhihu
        name: 知乎
        url: https://www.zhihu.com/people/malinkang
        weight: 9
        params:
            icon: brand-zhihu      
      - identifier: juejin
        name: 掘金
        url: https://juejin.cn/user/3051900006833694/
        weight: 11
        params:
            icon: brand-juejin
      - identifier: rss
        name: Rss
        url: index.xml
        weight: 12
        params:
            icon: rss

related:
    includeNewer: true
    threshold: 60
    toLower: false
    indices:
      - name: tags
        weight: 100

      - name: categories
        weight: 200

markup:
  goldmark:
      renderer:
          ## Set to true if you have HTML content inside Markdown
          unsafe: true
  tableOfContents:
      endLevel: 4
      ordered: true
      startLevel: 2
  highlight:
      noClasses: false
      codeFences: true
      guessSyntax: true
      lineNoStart: 1
      lineNos: true
      lineNumbersInTable: true
      tabWidth: 4
