baseURL: "https://blog.malinkang.com"
DefaultContentLanguage: "en"
languageCode: "en-us"
title: "Malinkang's Blog"
copyright: "This is a customized copyright."
theme:
  - diary
  - gallery
markup:
  highlight:
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: perldoc
    tabWidth: 4
  goldmark:
    renderer:
      unsafe: true
module:
  imports:
  - path: github.com/Runzelee/aplayer-hugo-module
  - path: github.com/martignoni/hugo-notice
params:
  subtitle: "记录生活"
  enableGitalk: false
  enableGiscus: true
  clarity: "abcdefghzd"
  enableOpenGraph: true
  enableTwitterCards: true
  gitalk:
    owner: user
    repo: "repo name"
    client_id: "your client id"
    client_secret: "your client secret"
  utterances:
    repo: "your repo"
    term: "[ENTER TERM HERE]"
    label: "your label"
    theme: github-light
  giscus:
    data_repo: malinkang/comments
    data-repo-id: R_kgDOG5PayQ
    data_category: General
    data_category_id: DIC_kwDOG5Payc4CUbl7
    data_mapping: pathname
    data_strict: "0"
    data_reactions_enabled: "1"
    data_emit_metadata: "0"
    data_input_position: bottom
    data_theme: light
    data_lang: zh-CN
    crossorigin: anonymous
taxonomies:
  tag: tags
  category: categories
menu:
  main:
    - url: /categories
      name: Categories
      weight: 2
    - url: /tags
      name: Tags
      weight: 3
    - url: /posts
      name: Archive
      weight: 1
    - url: /index.xml
      name: RSS Feed
      weight: 4
