name: blog sync
on:
  workflow_dispatch:
  schedule:
    - cron: "30 15 * * *" # 23:50 同步
jobs:
  sync:
    name: Sync
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: blog sync
        run: |
          python scripts/blog.py
