name: douban
on:
  workflow_dispatch:
  schedule:
  - cron: "0 0 * * *"

jobs:
  douban:
    name: Douban mark data sync
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # - name: movie
    #   uses: lizheming/doumark-action@master
    #   with:
    #     id: malinkang
    #     type: movie
    #     format: csv
    #     dir: ./data/douban
    # - name: book
    #   uses: lizheming/doumark-action@master
    #   with:
    #     id: malinkang
    #     type: book
    #     format: csv
    #     dir: ./data/douban

    # - name: Commit
    #   uses: EndBug/add-and-commit@v8
    #   with:
    #     author_name: malinkang
    #     author_email: linkang.ma@gmail.com
    #     committer_name: malinkang
    #     committer_email: linkang.ma@gmail.com
    # - name: movie_2_neodb
    #   uses: lizheming/doumark-action@master
    #   with:
    #     id: malinkang
    #     type: movie
    #     format: neodb
    #     neodb_token: ${{ secrets.neodb_token }}
    # - name: book_2_neodb
    #   uses: lizheming/doumark-action@master
    #   with:
    #     id: malinkang
    #     type: book
    #     format: neodb
    #     neodb_token: ${{ secrets.neodb_token }}