name: hugo sync
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0' # 每周日午夜执行
jobs:
  sync:
    name: Sync
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: hugo sync
        run: |
          python scripts/hugo.py "${{secrets.NOTION_TOKEN}}" "${{secrets.NOTION_DATABASE_ID}}" 
      - name: commit
        uses: EndBug/add-and-commit@v9
        with:
          branch: master
          author_name: malinkang
          author_email: linkang.ma@gmail.com
          committer_name: malinkang
          committer_email: linkang.ma@gmail.com
